spring.application.name=gestao-entrega

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:gestaoentregadb

jwt.key=hGY74h4GHwYG7EY4yG8WWEAPPQfsefryjiiHW8GHwhgNHVsngvzW
jwt.token.expiration=360000

spring.jpa.defer-datasource-initialization=true
